---
title: ""
output: 
    word_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)

all_di <- read.csv(here::here("analysis", "reports", "all_di.csv"), stringsAsFactors = F)

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 != s0,
         s0 != 1,
         !singletons,
         n0 != (s0 + 1)) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset))

```


# Table S4. Proportion of sites with highly skewed or uneven SADs 

```{r results table, echo = F}

overall_skew_results <- all_di %>%
  filter(s0 > 2, skew_unique > 20) %>%
  mutate(high_skew = skew_percentile_excl > 95) %>%
  group_by(Dataset) %>%
  summarize(proportion_skew_high = mean(high_skew),
            nsites_skew = dplyr::n())

overall_simpson_results <- all_di %>%
  filter(simpson_unique > 20) %>%
  mutate(low_even = simpson_percentile < 5) %>%
  group_by(Dataset) %>%
  summarize(proportion_even_low = mean(low_even),
            nsites_even = dplyr::n())

overall_results <- left_join(overall_skew_results, overall_simpson_results) %>%
  rename("Proportion of communities with skewness above 95th percentile" = proportion_skew_high,
         "Number of communities analyzed for skewness" = nsites_skew,
         "Proportion of communities with evenness below 5th percentile" = proportion_even_low,
         "Number of communities analyzed for evenness" = nsites_even)
```

```{r}
overall_results

# 
# overall_skew_results2 <- all_di %>%
#   mutate(Dataset = ifelse(dat == "fia", "Forest Inventory and Analysis", "Other datasets")) %>%
#   filter(s0 > 2, skew_unique > 20) %>%
#   mutate(high_skew = skew_percentile_excl > 95) %>%
#   group_by(Dataset) %>%
#   summarize(proportion_skew_high = mean(high_skew),
#             nsites_skew = dplyr::n())
# 
# overall_simpson_results2 <- all_di %>%
#   filter(simpson_unique > 20) %>%
#   mutate(Dataset = ifelse(dat == "fia", "Forest Inventory and Analysis", "Other datasets")) %>%
#   mutate(low_even = simpson_percentile < 5) %>%
#   group_by(Dataset) %>%
#   summarize(proportion_even_low = mean(low_even),
#             nsites_even = dplyr::n())
# 
# overall_results2 <- left_join(overall_skew_results2, overall_simpson_results2) %>%
#   rename("Proportion of communities with skewness above 95th percentile" = proportion_skew_high,
#          "Number of communities analyzed for skewness" = nsites_skew,
#          "Proportion of communities with evenness below 5th percentile" = proportion_even_low,
#          "Number of communities analyzed for evenness" = nsites_even)

#overall_results2


```


