---
title: "Between-dataset comparisons"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

all_statevars <- list() 

# datasets <- c("bbs", "fia", "gentry", "mcdb", "misc_abund_short", "portal_plants")

datasets <- c("fia", "gentry", "mcdb", "misc_abund_short", "portal_plants")

for(i in 1:length(datasets)) {
  
  this_dataset = datasets[i]
  if(this_dataset == "misc_abund_short") {
    cache_loc = "miscabund"
  } else {
    cache_loc = this_dataset
  }
  
  ## Set up the cache and config
  db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", paste0("drake-cache-", cache_loc, ".sqlite")))
  cache <- storr::storr_dbi("datatable", "keystable", db)
  
  this_dat <- readd(paste0("dat_s_dat_", this_dataset), cache = cache, character_only = T)
  
  all_statevars[[i]] <- get_statevars(this_dat)
  
  all_statevars[[i]]$site <- as.character(all_statevars[[i]]$site)
  
  DBI::dbDisconnect(db)
  rm(cache)
  rm(db)
  rm(this_dat)
}

names(all_statevars) <- datasets

all_statevars <- bind_rows(all_statevars)

all_extremes <- all_statevars %>%
  group_by(dat, singletons) %>%
  summarize(min_s0 = min(s0),
            min_n0 = min(n0),
            max_s0 = max(s0),
            max_n0 = max(n0)) %>%
  ungroup()

```

## Extremes by dataset

Here are the spaces occupied by each dataset
```{r statevars}
extrema_plot <- ggplot(data = all_extremes, aes(x = max_s0, y = max_n0, color = dat)) +
  geom_point(aes(x = min_s0, y = min_n0)) +
  geom_point(aes(x = max_s0, y = max_n0)) +
  facet_wrap(vars(singletons)) +
  scale_color_viridis_d(end = .8) +
  theme_bw() +
  xlim(0, max(all_extremes$max_s0)) +
  ylim(0, max(all_extremes$max_n0))

extrema_plot

```

```{r occupancy}

all_statevars <- all_statevars %>%
  filter(!singletons) %>%
  mutate(
    # in_bbs = between(s0, filter(all_extremes, dat == "bbs", singletons == F)$min_s0[1], filter(all_extremes, dat == "bbs", singletons == F)$max_s0[1]) + between(n0, filter(all_extremes, dat == "bbs", singletons == F)$min_n0[1], filter(all_extremes, dat == "bbs", singletons == F)$max_n0[1]) == 2,
    in_fia = between(s0, filter(all_extremes, dat == "fia", singletons == F)$min_s0[1], filter(all_extremes, dat == "fia", singletons == F)$max_s0[1]) + between(n0, filter(all_extremes, dat == "fia", singletons == F)$min_n0[1], filter(all_extremes, dat == "fia", singletons == F)$max_n0[1]) == 2,
    in_gentry = between(s0, filter(all_extremes, dat == "gentry", singletons == F)$min_s0[1], filter(all_extremes, dat == "gentry", singletons == F)$max_s0[1]) + between(n0, filter(all_extremes, dat == "gentry", singletons == F)$min_n0[1], filter(all_extremes, dat == "gentry", singletons == F)$max_n0[1]) == 2,
    in_mcdb = between(s0, filter(all_extremes, dat == "mcdb", singletons == F)$max_s0[1], filter(all_extremes, dat == "mcdb", singletons == F)$max_s0[1]) + between(n0, filter(all_extremes, dat == "mcdb", singletons == F)$min_n0[1], filter(all_extremes, dat == "mcdb", singletons == F)$max_n0[1]) == 2,
    in_misc = between(s0, filter(all_extremes, dat == "misc_abund_short", singletons == F)$max_s0[1], filter(all_extremes, dat == "misc_abund_short", singletons == F)$max_s0[1]) + between(n0, filter(all_extremes, dat == "misc_abund_short", singletons == F)$min_n0[1], filter(all_extremes, dat == "misc_abund_short", singletons == F)$max_n0[1]) == 2,
    in_portal = between(s0, filter(all_extremes, dat == "portal_plants", singletons == F)$max_s0[1], filter(all_extremes, dat == "portal_plants", singletons == F)$max_s0[1]) + between(n0, filter(all_extremes, dat == "portal_plants", singletons == F)$min_n0[1], filter(all_extremes, dat == "portal_plants", singletons == F)$max_n0[1]) == 2
    ) %>%
  # mutate(total_in = in_bbs + in_fia + in_gentry + in_mcdb + in_misc + in_portal)
  mutate(total_in =in_fia + in_gentry + in_mcdb + in_misc + in_portal)

```

```{r intersection plot}

intersection_plot <- ggplot(data = filter(all_statevars, singletons == FALSE, total_in > 1), aes(x = s0, y = n0, color = as.factor(total_in))) +
  geom_point(alpha = .2) +
  theme_bw() +
  scale_color_viridis_d(option = "plasma", end = .9)
intersection_plot

```
