---
title: "Between-dataset comparisons"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

all_di <- list() 
datasets <- c("bbs", "fia_short", "gentry", "mcdb", "misc_abund_short", "portal_plants")

#datasets <- c("fia", "gentry", "mcdb", "misc_abund_short", "portal_plants")

for(i in 1:length(datasets)) {
  
  this_dataset = datasets[i]
  if(this_dataset == "misc_abund_short") {
    cache_loc = "miscabund"
  } else if(this_dataset == "fia_short") {
    
    cache_loc = "fia"
  } else {
    cache_loc = this_dataset
  }
  
  ## Set up the cache and config
  db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", paste0("drake-cache-", cache_loc, ".sqlite")))
  cache <- storr::storr_dbi("datatable", "keystable", db)
  
  if("all_di" %in% cached(cache = cache)) {
    all_di[[i]] <- readd(all_di, cache = cache)
  } else {
    all_di_names <- cached(cache = cache)[ which(grepl(cached(cache = cache), pattern = "all_di_s_"))]
    all_di_list <- lapply(all_di_names, FUN = readd, cache = cache, character_only =T)
    names(all_di_list) <- all_di_names
    all_di[[i]] <- bind_rows(all_di_list)
    rm(all_di_names)
    rm(all_di_list)
  }
  all_di[[i]] <- filter(all_di[[i]], source == "observed")
  
  this_dat <- readd(paste0("dat_s_dat_", this_dataset), cache = cache, character_only = T)
  sv <- get_statevars(this_dat)
  all_di[[i]] <- left_join(all_di[[i]], sv, by = c("sim", "site", "source", "singletons", "dat"))
  
  
  DBI::dbDisconnect(db)
  rm(cache)
  rm(db)
}


all_di <- bind_rows(all_di)


```

```{r overall percentile heatmap}

overall_heatmap_skew <- ggplot(data = all_di, aes(x = s0, y = n0, color = skew_percentile)) +
  geom_point(alpha = .2) +
  theme_bw() +
  scale_color_viridis_c(option = "plasma", begin = .1, end = .8, direction = -1) +
  facet_wrap(vars(singletons)) +
  ggtitle("Skewness Percentile") +
  theme(legend.position = "bottom")


overall_heatmap_simpson <- ggplot(data = all_di, aes(x = s0, y = n0, color = simpson_percentile)) +
  geom_point(alpha = .2) +
  theme_bw() +
  scale_color_viridis_c(option = "plasma", begin = .1, end = .8)+
  facet_wrap(vars(singletons)) +
  ggtitle("Simpson's Percentile")+
  theme(legend.position = "bottom")


overall_heatmap_skew_zoomed <- overall_heatmap_skew +
  ylim(0, 5000) +
  xlim(0, 250)+
  theme(legend.position = "none")



overall_heatmap_simpson_zoomed <- overall_heatmap_simpson +
  ylim(0, 5000) +
  xlim(0, 250)+
  theme(legend.position = "none")

gridExtra::grid.arrange(grobs = list(overall_heatmap_skew, overall_heatmap_skew_zoomed), nrow= 1)
gridExtra::grid.arrange(grobs = list(overall_heatmap_simpson, overall_heatmap_simpson_zoomed), nrow= 1)

```

Broken out by dataset

```{r dataset heatmaps}

dat_heatmap_skew <-  ggplot(data = filter(all_di, !singletons), aes(x = s0, y = n0, color = skew_percentile)) +
  geom_point(alpha = .4) +
  theme_bw() +
  scale_color_viridis_c(option = "plasma", begin = .1, end = .8, direction = -1)+
  facet_wrap(vars(dat), scales = "free") +
  ggtitle("Skew Percentile")+
  theme(legend.position = "bottom")
dat_heatmap_skew

dat_heatmap_simpson <-  ggplot(data = filter(all_di, !singletons), aes(x = s0, y = n0, color = simpson_percentile)) +
  geom_point(alpha = .4) +
  theme_bw() +
  scale_color_viridis_c(option = "plasma", begin = .1, end = .8)+
  facet_wrap(vars(dat), scales = "free") +
  ggtitle("Simpson's Percentile")+
  theme(legend.position = "bottom")
dat_heatmap_simpson
```

Against S0

```{r s0 percentile}

overall_s0_skew <- ggplot(data = filter(all_di, !singletons), aes(x = s0, y = skew_percentile)) +
  geom_point(alpha = .1) +
  geom_smooth(method = "lm", se = F, color = "pink") +
  theme_bw() +
  ggtitle("Skew percentile")
overall_s0_skew

dat_s0_skew <- overall_s0_skew +
  facet_wrap(vars(dat), scales = "free")
dat_s0_skew


overall_s0_simpson <- ggplot(data = filter(all_di, !singletons), aes(x = s0, y = simpson_percentile)) +
  geom_point(alpha = .1) +
  geom_smooth(method = "lm", se = F, color = "pink") +
  theme_bw() +
  ggtitle("Simpson percentile")
overall_s0_simpson

dat_s0_simpson <- overall_s0_simpson +
  facet_wrap(vars(dat), scales = "free")
dat_s0_simpson

```
