---
title: "Dataset-level report"
output: 
  github_document:
    html_preview: false
params:
  dataset_name: ["mcdb"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

this_dataset <- params$dataset_name

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", paste0("drake-cache-", this_dataset, ".sqlite")))
cache <- storr::storr_dbi("datatable", "keystable", db)

dat <- readd(paste0("dat_s_dat_", this_dataset), cache = cache, character_only = T)
loadd(all_di, cache = cache)

```
# This dataset is `r this_dataset`.

## State variables and change with singletons

Here is a plot of the distribution of S and N in this dataset, and S and N if we estimate the true number of species.

```{r statevars}

sv <- get_statevars(dat)

statevars_plot <- ggplot(data = sv, aes(x = s0, y = n0, color = singletons)) +
  geom_point(alpha = .5) +
  theme_bw() +
  facet_wrap(vars(singletons)) +
  scale_color_viridis_d(end = .5) +
  ggtitle("State variables")

statevars_plot
```

Here is a plot of how many species were added to each dataset by estimating the true number of species.

```{r sv change}
sv_singles <- filter(sv, singletons == TRUE) %>%
  select(-singletons) %>%
  rename(singletons_s0 = s0,
         singletons_n0 = n0)

sv_change <- filter(sv, singletons == FALSE) %>%
  select(-singletons) %>%
  left_join(sv_singles, by = c("site", "dat", "sim", "source")) %>%
  mutate(s0_change = singletons_s0 - s0,
         n0_change = singletons_n0 - n0) %>%
  select(-singletons_s0, -singletons_n0)

sv_change_plot <- ggplot(data = sv_change, aes(x = s0, y = n0, color = log(s0_change))) +
  geom_point(alpha = .5) +
  theme_bw() +
  scale_color_viridis_c(option = "plasma", end = .75, direction = -1) +
  ggtitle("State variable change")

sv_change_plot
```

## Position (%ile) of empirical SADs within FS

```{r empirical positions}

skew_plot <- ggplot(data = filter(all_di, source == "observed"), aes(x= singletons, y = skew_percentile)) +
  geom_boxplot() +
  theme_bw() +
  ggtitle("Skewness percentile") +
  ylim(0, 100)

simpson_plot <- ggplot(data = filter(all_di, source == "observed"), aes(x= singletons, y = simpson_percentile)) +
  geom_boxplot() +
  theme_bw() +
  ggtitle("Simpson percentile") +
  ylim(0, 100)

gridExtra::grid.arrange(grobs = list(skew_plot, simpson_plot), ncol = 2)
```

```{r cleanup}

DBI::dbDisconnect(db)
rm(cache)
```
