---
title: "Synthesis report"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)

all_di <- read.csv(here::here("analysis", "reports", "all_di.csv"), stringsAsFactors = F)

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log150_nparts = log(gmp:::as.double.bigz(nparts), base = 150)) %>%
  mutate(prop_found = exp(log_nsamples - log_nparts)) %>%
  mutate(found_all = prop_found==1) %>%
  filter(s0 >= 2,
         n0 > s0,
         dat != "fia_small")
```

# Datasets in S and N space

Here is where our communities fall in S and N space:

```{r datasets in s and n space}
ggplot(filter(all_di, singletons == F), aes(x = log(s0), y = log(n0), color = dat)) +
  geom_point(alpha = .8) +
  theme_bw() +
  theme(legend.position = "top") + scale_color_viridis_d()

```

Here is how that translates into the size of the feasible set:

```{r size of fs}
ggplot(filter(all_di, singletons == F), aes(x = log(s0), y = log(n0), color = log150_nparts)) +
  geom_point(alpha = .5) +
  theme_bw() +
  theme(legend.position = "top") + scale_color_viridis_c(option = "magma", end = .9, begin = .1)

ggplot(filter(all_di, singletons == F), aes(x = log_nparts, y = ..count..)) +
  geom_density() +
  theme_bw() +
  geom_vline(xintercept = c(10, 15))


ggplot(filter(all_di, singletons == F), aes(x = log_nparts, y = ..count..)) +
  geom_density() +
  theme_bw() +
  geom_vline(xintercept = c(10, 15)) +
  facet_wrap(vars(dat), scales = "free")


```

## Resrict to sizes found in FIA

```{r fia limits}


fia_max_s <- max(filter(all_di, !singletons, dat == "fia_short")$s0)
fia_max_n <- max(filter(all_di,!singletons,  dat == "fia_short")$n0)

fia_sized <- filter(all_di, s0 <= fia_max_s, !singletons, n0 <= fia_max_n) %>%
  mutate(fia_yn = dat == "fia_short")

ggplot(fia_sized, aes(x = log(s0), y= log(n0), color = dat)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_d()

mean(fia_sized$dat == "fia_short")

```

95% of the datasets with state variables comparable to the FIA ranges are FIA. 

```{r fia sized hists}

ggplot(filter(fia_sized, s0 > 2), aes(x = skew_percentile)) +
  geom_histogram()


ggplot(filter(fia_sized, s0 > 2), aes(x = skew_percentile)) +
  geom_histogram() +
  facet_wrap(vars(fia_yn), scales = "free_y")




ggplot(filter(fia_sized, s0 > 2), aes(x = simpson_percentile)) +
  geom_histogram()


ggplot(filter(fia_sized, s0 > 2), aes(x = simpson_percentile)) +
  geom_histogram() +
  facet_wrap(vars(fia_yn), scales = "free_y")

```


```{r on map}


ggplot(fia_sized, aes(x = log(s0), y= log(n0), color = skew_percentile)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c()


ggplot(fia_sized, aes(x = log(s0), y= log(n0), color = simpson_percentile)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c()
```
