---
title: "KDE report"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

this_dataset <- "kde"

if(this_dataset == "misc_abund_short") {
  cache_loc = "miscabund"
} else if (this_dataset == "fia_short") {
  cache_loc = "fia" 
} else {
  cache_loc = this_dataset
}

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", paste0("drake-cache-", cache_loc, ".sqlite")))
cache <- storr::storr_dbi("datatable", "keystable", db)

all_di <- readd(all_di, cache = cache)


```
# This dataset is `r this_dataset`.

```{r make kde}
di <- filter(all_di, singletons == FALSE)

skew_kde <- data.frame(x = density(filter(di, source == "sampled")$skew)$x,
                       y = density(filter(di, source == "sampled")$skew)$y) %>%
  mutate(y = y / sum(y))

skewplot <- ggplot(data = skew_kde, aes(x = x, y = y)) +
  geom_point() +
  geom_vline(xintercept = filter(di, source == "observed")$skew[1]) +
  theme_bw()
skewplot

skewdensity <- skew_kde$y [ which.min(abs(skew_kde$x - filter(di, source == "observed")$skew[1]))]
skewdensity


simpson_kde <- data.frame(x = density(filter(di, source == "sampled")$simpson, from = 0, to = 1)$x,
                       y = density(filter(di, source == "sampled")$simpson, from = 0, to = 1)$y) %>%
  mutate(y = y / sum(y))

simpsonplot <- ggplot(data = simpson_kde, aes(x = x, y = y)) +
  geom_point() +
  geom_vline(xintercept = filter(di, source == "observed")$simpson[1]) +
  theme_bw()
simpsonplot

simpsondensity <- simpson_kde$y [ which.min(abs(simpson_kde$x - filter(di, source == "observed")$simpson[1]))]
simpsondensity
```


```{r cleanup}

DBI::dbDisconnect(db)
rm(cache)
```
