---
title: "Explaining and exploring the 95% interval metric"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", "drake-cache-net.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")
knitr::opts_chunk$set(fig.width=4, fig.height=3, warning = FALSE, message = FALSE) 
```


```{r real data, include=FALSE}

all_di <- read.csv(here::here("analysis", "reports", "all_di.csv"), stringsAsFactors = F)

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 > s0,
         !singletons,
         s0 > 1,
         dat %in% c("bbs", "fia_short", "fia_small", "gentry", "mcdb", "misc_abund_short")) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat))



ggplot(filter(all_di, s0> 2), aes(skew_percentile_excl)) +
  geom_histogram(bins = 100) +
  facet_wrap(vars(dat), scales = "free_y")


ggplot(filter(all_di, s0> 2, skew_unique > 100), aes(skew_percentile_excl)) +
  geom_histogram(bins = 100) +
  facet_wrap(vars(dat), scales = "free_y")



```
