---
title: "Regressions"
output: 
  github_document
params:
  on_hpg: [FALSE]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

if(params$on_hpg) {
  
  all_di <- list() 
  datasets <- c("bbs", "fia_short", "gentry", "mcdb", "misc_abund_short", "portal_plants")
  
  #datasets <- c("fia", "gentry", "mcdb", "misc_abund_short", "portal_plants")
  
  for(i in 1:length(datasets)) {
    
    this_dataset = datasets[i]
    if(this_dataset == "misc_abund_short") {
      cache_loc = "miscabund"
    } else if(this_dataset == "fia_short") {
      
      cache_loc = "fia"
    } else {
      cache_loc = this_dataset
    }
    
    ## Set up the cache and config
    db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analysis", "drake", paste0("drake-cache-", cache_loc, ".sqlite")))
    cache <- storr::storr_dbi("datatable", "keystable", db)
    
    all_di[[i]] <- readd(all_di_obs, cache = cache)
    
    all_di[[i]] <- filter(all_di[[i]], source == "observed")
    
    this_dat <- readd(paste0("dat_s_dat_", this_dataset), cache = cache, character_only = T)
    sv <- get_statevars(this_dat)
    all_di[[i]] <- left_join(all_di[[i]], sv, by = c("sim", "site", "source", "singletons", "dat"))
    
    
    DBI::dbDisconnect(db)
    rm(cache)
    rm(db)
  }
  
  
  all_di <- bind_rows(all_di)
  
  write.csv(all_di, "all_di.csv", row.names = F)
} else {
  all_di <- read.csv(here::here("analysis", "reports", "all_di.csv"), stringsAsFactors = F)
}

di_summary <- all_di %>%
  filter(nsamples >= 2000, !singletons) %>%
  mutate(avg_n = n0 / s0,
         skew_pp = skew_percentile / 100.01,
         simp_pp = simpson_percentile/100.01)

```


Filtering to nsamples >= 2000, not singletons.

### Supposed correlates

#### Average abundance (N/S)

```{r avg n}

avg_n_plot <- ggplot(data = di_summary, aes(x = avg_n)) +
  geom_histogram() +
  facet_wrap(vars(dat), scales = "free") +
  theme_bw() +
  ggtitle("Average abundance")
print(avg_n_plot)

avg_n_boxplot <- ggplot(data = di_summary, aes(x= dat, y = avg_n)) +
  geom_boxplot() +
  theme_bw() +
  ggtitle("Average abundance") 

print(avg_n_boxplot)


avg_n_boxplot_log <- ggplot(data = di_summary, aes(x= dat, y = log(avg_n))) +
  geom_boxplot() +
  theme_bw() +
  ggtitle("Average abundance") 

print(avg_n_boxplot_log)
```

```{r means and sds}
skew_mean_plot <- ggplot(data = di_summary, aes(x = dat, y = skew_mean)) +
  geom_boxplot() +
  theme_bw()
skew_sd_plot <- ggplot(data = di_summary, aes(x = dat, y = skew_sd)) +
  geom_boxplot() +
  theme_bw()
skew_m_sd_plot <- ggplot(data = di_summary, aes(x = skew_mean, y = skew_sd, color = dat)) +
  geom_point(alpha = .2) +
  theme_bw()

skew_mean_plot
skew_sd_plot
skew_m_sd_plot

simpson_mean_plot <- ggplot(data = di_summary, aes(x = dat, y = simpson_mean)) +
  geom_boxplot() +
  theme_bw()
simpson_sd_plot <- ggplot(data = di_summary, aes(x = dat, y = simpson_sd)) +
  geom_boxplot() +
  theme_bw()
simpson_m_sd_plot <- ggplot(data = di_summary, aes(x = simpson_mean, y = simpson_sd, color = dat)) +
  geom_point(alpha = .2) +
  theme_bw()

simpson_mean_plot
simpson_sd_plot
simpson_m_sd_plot

```

The different datasets are on dramatically different scales of average abundance, although it looks like a lot of that is outliers in misc_abund.

### Correlation plots

#### Average abundance
```{r avg n vis, fig.dim = c(8,8)}

skew_avgn_plot <- ggplot(data = di_summary, aes(x = avg_n, y = skew_percentile)) +
  geom_point(size = 1, alpha = .2) +
  facet_wrap(vars(dat), scales = "free_x") +
  theme_bw() +
  ggtitle("Skew v Avg N")
print(skew_avgn_plot)


simpson_avgn_plot <- ggplot(data = di_summary, aes(x = avg_n, y = simpson_percentile)) +
  geom_point(size = 1, alpha = .2) +
  facet_wrap(vars(dat), scales = "free_x") +
  theme_bw() +
  ggtitle("Simpson v Avg N")
print(simpson_avgn_plot)

```

#### Mean and sd

```{r mean sd vis, fix.dim = c(8, 8)}

skew_mean_plot <- ggplot(data = di_summary, aes(x = skew_mean, y = skew_percentile)) +
  geom_point(size = 1, alpha = .2) +
  facet_wrap(vars(dat), scales = "free") +
  theme_bw() +
  ggtitle("Skew v Mean skew")
print(skew_mean_plot)


skew_sd_plot <- ggplot(data = di_summary, aes(x = skew_sd, y = skew_percentile)) +
  geom_point(size = 1, alpha = .2) +
  facet_wrap(vars(dat), scales = "free") +
  theme_bw() +
  ggtitle("Skew v sd skew")
print(skew_sd_plot)

simpson_mean_plot <- ggplot(data = di_summary, aes(x = simpson_mean, y = simpson_percentile)) +
  geom_point(size = 1, alpha = .2) +
  facet_wrap(vars(dat), scales = "free") +
  theme_bw() +
  ggtitle("simpson v Mean simpson")
print(simpson_mean_plot)


simpson_sd_plot <- ggplot(data = di_summary, aes(x = simpson_sd, y = simpson_percentile)) +
  geom_point(size = 1, alpha = .2) +
  facet_wrap(vars(dat), scales = "free") +
  theme_bw() +
  ggtitle("simpson v sd simpson")
print(simpson_sd_plot)


```


### Beta regression

#### Average abundance

```{r betareg avg n}
library(betareg)

di_summary$skew_pp[ which(di_summary$skew_pp == 0)] <- .00000001
di_summary$simp_pp[ which(di_summary$simp_pp == 0)] <- .00000001

avgn_br_skew <- betareg(skew_pp ~ avg_n + dat, data = di_summary)
summary(avgn_br_skew)
plot(avgn_br_skew)

```
