---
title: "Comparing to lognormal, Poisson, exponential"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

knitr::opts_chunk$set(fig.width=4, fig.height=3, warning = FALSE, message = FALSE) 

theme_set(theme_bw())
compare_props_off2 <- function(focal_sim, fs_df, ncomps = 100) {

  fs_df$sim_char = as.character(fs_df$sim)

  if(focal_sim != -99) {
    fs_df <- dplyr::filter(fs_df, sim > 0)
  }

  nsims <- unique(fs_df$sim_char)[ which(unique(fs_df$sim_char) != as.character(focal_sim))]

  if(length(nsims) == 0) {
    return(data.frame(focal_sim = focal_sim, mean_po_comparison = NA, n_po_comparisons = 0))
  }

  focal_sad <- dplyr::filter(fs_df, sim == focal_sim)

  compare_sims <- sample(nsims, size = min(length(nsims), ncomps), replace =F)

  compare_sads <- dplyr::filter(fs_df, sim_char %in% compare_sims)

  compare_props <- compare_sads %>%
    dplyr::group_by(sim) %>%
    dplyr::summarize(prop_off = proportion_off(t(data.frame(abund, focal_sad$abund)))) %>%
    dplyr::ungroup()

  return(compare_props)
}

```


```{r}

fs <- read.csv(here::here("analysis", "rev_prototyping", "gentry_82_fs.csv"))
fs_pc <- read.csv(here::here("analysis", "rev_prototyping", "fs_pc_fs_82.csv"))

ct_sim <- filter(fs_pc, mean_po_comparison == min(fs_pc$mean_po_comparison))

ggplot(filter(fs, sim %in% fs_pc$focal_sim), aes(rank, abund, group = sim)) +
  geom_line() + scale_y_log10() + geom_line(data = filter(fs, sim ==ct_sim$focal_sim[1]), color = "red")

ct_sad <- filter(fs, sim == ct_sim$focal_sim[1])
real_sad <- filter(fs, sim < 0)
ggplot(ct_sad, aes(rank, abund)) +
  geom_line() +
  geom_line(data = real_sad, inherit.aes = T, color='blue')

real_po <- proportion_off(t(data.frame(real_sad$abund, ct_sad$abund)))
sim_po <- compare_props_off2(ct_sad$sim[1], fs, ncomps = 3999)


ggplot(sim_po, aes(prop_off)) +
  geom_histogram() +
  geom_vline(xintercept = real_po)
```

```{r}

po_central_tendency <- function(fs_df, fs_po_df) {
  
  ct_sim <- dplyr::filter(fs_po_df, mean_po_comparison == min(fs_po_df$mean_po_comparison))$focal_sim[1]
  
  ct_pos <- compare_props_off_full(ct_sim, fs_df, ncomps = length(unique(fs_df$sim)) - 2) %>%
    dplyr::distinct()
  
  real_po <- proportion_off(t(data.frame(dplyr::filter(fs_df, source == "observed")$abund, dplyr::filter(fs_df, sim == ct_sim)$abund)))

  out <- fs_df %>%
    dplyr::filter(source == "observed") %>%
    dplyr::select(source, dat, site, singletons, s0, n0, sim, nparts) %>%
    dplyr::distinct() %>%
    dplyr::mutate(
      real_po = real_po,
      best_po_sim = ct_sim,
      sim_devs_from_best = mean(ct_pos$prop_off),
      ncomparisons = nrow(ct_pos),
      real_po_percentile = get_percentile(real_po, ct_pos$prop_off),
      real_po_percentile_excl = get_percentile(real_po, ct_pos$prop_off, incl = F)
    )

}

```
