---
title: "Comparing to lognormal, Poisson, exponential"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

knitr::opts_chunk$set(fig.width=4, fig.height=3, warning = FALSE, message = FALSE) 

theme_set(theme_bw())


all_di <- read.csv(here::here("analysis", "reports", "all_di.csv"), stringsAsFactors = F)

mcdb_ct <- read.csv(here::here("mcdb_cts.csv"))



all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 != s0,
         s0 != 1,
         !singletons,
         n0 != (s0 + 1)) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) %>%
  filter(dat == "mcdb") %>%
  left_join(mcdb_ct)
```


```{r}

ggplot(all_di, aes(sim_pos_from_best)) +
  geom_histogram()


ggplot(all_di, aes(sim_pos_from_best, real_po)) +
  geom_point() +
  geom_line(aes(sim_pos_from_best, sim_pos_from_best)) 


ggplot(all_di, aes(real_po_percentile_excl)) + geom_histogram()

ggplot(all_di, aes(nparts, sim_pos_from_best)) +
  geom_point() +
  scale_x_log10()

```


```{r}

ggplot(all_di, aes(sim_r2_from_best_median)) +
  geom_histogram()


ggplot(all_di, aes(sim_r2_from_best_median, real_r2)) +
  geom_point() +
  geom_line(aes(sim_r2_from_best_median, sim_r2_from_best_median)) +
  ylim(0,1)


ggplot(all_di, aes(real_po_percentile_excl)) + geom_histogram()

ggplot(all_di, aes(nparts, sim_r2_from_best_median)) +
  geom_point() +
  scale_x_log10()

```
