---
title: "Updated results"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
       toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

knitr::opts_chunk$set(fig.width=4, fig.height=3, warning = FALSE, message = FALSE) 

theme_set(theme_bw())


all_di <- read.csv(here::here("analysis", "rev_prototyping", "all_di.csv"), stringsAsFactors = F)

all_ct <-  read.csv(here::here("analysis", "rev_prototyping", "all_ct.csv"), stringsAsFactors = F)


fia_ct <- read.csv(here::here("fia_cts.csv"))

all_ct <- rbind(all_ct, fia_ct)
all_ct <- all_ct %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat))

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 != s0,
         s0 != 1,
         !singletons,
         n0 != (s0 + 1)) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) %>%
  left_join(all_ct) 

all_di <- all_di %>%
  group_by_all() %>%
  mutate(real_po_percentile_mean = mean(real_po_percentile, real_po_percentile_excl)) %>%
  ungroup()

all_di <- all_di %>%
  mutate(in_fia = ifelse(Dataset == "FIA", "FIA", "Other datasets"))

```


## Comparing observed to the baseline

### Central tendency

```{r}
# 
# ggplot(all_di, aes(sim_pos_from_best)) +
#   geom_histogram() +
#   facet_wrap(vars(dat), scales = "free_y") 
# 
# ggplot(all_di, aes(real_po_percentile_excl)) + geom_histogram() +
#   facet_wrap(vars(dat), scales = "free_y") + geom_vline(xintercept = 95)

ggplot(all_di, aes(real_po_percentile_mean)) + geom_histogram() +
  facet_wrap(vars(dat), scales = "free_y") + geom_vline(xintercept = 95)


all_di %>%
  group_by(dat) %>%
  summarize(prop_high_po = mean(real_po_percentile_excl > 95, na.rm = T),
            nsites = dplyr::n())



all_di %>%
  group_by(in_fia) %>%
  summarize(prop_high_po = mean(real_po_percentile_excl > 95, na.rm = T),
            nsites = dplyr::n())


ggplot(all_di, aes(sim_pos_from_best, real_po, color = real_po_percentile_excl > 95)) +
  geom_point(alpha = .3) +
  geom_abline(slope = 1, intercept = 0) +
  theme(legend.position = "top") +
  scale_color_viridis_d(end = .8) +
  facet_wrap(vars(dat), scales = "fixed")

ggplot(all_di, aes(sim_pos_from_best, real_po, color = real_po_percentile_excl > 95)) +
  geom_point(alpha = .3) +
  geom_abline(slope = 1, intercept = 0) +
  theme(legend.position = "top") +
  scale_color_viridis_d(end = .8)# +
#  facet_wrap(vars(dat), scales = "fixed")

filter(all_di, real_po_percentile_excl > 95) %>%
  mutate(real_to_mean_sim_po_ratio = real_po / sim_pos_from_best,
         real_to_mean_sim_po_difference = real_po - sim_pos_from_best,
         real_to_mean_sim_po_logratio = log(real_po / sim_pos_from_best)) %>%
  select(real_to_mean_sim_po_ratio, real_to_mean_sim_po_difference) %>%
  summarize_all(.funs = list(min = min,max = max))
```


### Shape metrics

```{r, fig.dim = c(12,12)}

all_di_shapes_long <- all_di  %>%
  filter(nparts > 40) %>%
  #mutate(dat = ifelse(nparts < 1000, paste0(dat, "_small"), dat)) %>%
  select(dat, skew_percentile, skew_percentile_excl, simpson_percentile, simpson_percentile_excl, shannon_percentile, shannon_percentile_excl, nsingletons_percentile, nsingletons_percentile_excl) %>%
  rename(skew = skew_percentile,
         skewX = skew_percentile_excl,
         simp = simpson_percentile,
         simpX = simpson_percentile_excl,
         shan = shannon_percentile,
         shanX = shannon_percentile_excl,
         nsng = nsingletons_percentile,
         nsngX = nsingletons_percentile_excl) %>%
  mutate(skewM = (skew + skewX) / 2,
         simpM = (simp+ simpX)/2,
         shanM = (shan+ shanX)/2,
         nsngM = (nsng+ nsngX)/2) %>%
  tidyr::pivot_longer(-dat, names_to = "metric", values_to = "value") %>%
  mutate(metric_name = substr(metric, 0, 4),
         metric_mod = ifelse(substr(metric, 5, 5) == "X", "excl", ifelse(substr(metric, 5,5) == "M", "mean", "incl")))

all_di_shapes_high <- all_di_shapes_long %>%
  filter(metric_mod == "excl") %>%
  group_by(dat, metric_name) %>%
  summarize(proportion_high = mean(value > 97.5),
            n = dplyr::n())

all_di_shapes_high %>%
  tidyr::pivot_wider(id_cols = c(dat, n), names_from = metric_name, values_from = proportion_high) %>% mutate(dir = "HIGH")


all_di_shapes_low <- all_di_shapes_long %>%
  filter(metric_mod == "incl") %>%
  group_by(dat, metric_name) %>%
  summarize(proportion_low = mean(value <2.5))


all_di_shapes_low %>%
  tidyr::pivot_wider(id_cols = dat, names_from = metric_name, values_from = proportion_low) %>%
  mutate(dir = "LOW")



all_di_shapes_high <- all_di_shapes_long %>%
  mutate(in_fia = ifelse(dat == "fia", "FIA", "Other")) %>%
  filter(metric_mod == "excl") %>%
  group_by(in_fia, metric_name) %>%
  summarize(proportion_high = mean(value >97.5))


all_di_shapes_high %>%
  tidyr::pivot_wider(id_cols = in_fia, names_from = metric_name, values_from = proportion_high) %>%
  mutate(dir = "high")

all_di_shapes_low <- all_di_shapes_long %>%
  mutate(in_fia = ifelse(grepl("fia", dat), "FIA", "Other")) %>%
  filter(metric_mod == "incl") %>%
  group_by(in_fia, metric_name) %>%
  summarize(proportion_low = mean(value <2.5))


all_di_shapes_low %>%
  tidyr::pivot_wider(id_cols = in_fia, names_from = metric_name, values_from = proportion_low) %>%
  mutate(dir = "LOW")

```

### For very small communities


```{r}
all_di <- all_di %>%
  mutate(very_small = nparts < 2000)

```


#### Central tendency

```{r}

all_di %>%
  filter(nparts > 20) %>%
  group_by(dat, very_small) %>%
  summarize(prop_high_po = mean(real_po_percentile_excl > 97.5, na.rm = T),
            nsites = dplyr::n()) %>%
  tidyr::pivot_wider(id_cols = dat, names_from = very_small, values_from = c(prop_high_po, nsites))


ggplot(filter(all_di, dat %in% c("fia", "mcdb", "misc_abund"), nparts > 20), aes(real_po_percentile_mean)) +
  geom_histogram(bins = 40) +
  facet_wrap(vars(dat, very_small), scales = "free_y", ncol = 2)
```
#### Shape metrics

```{r}

all_di_shapes_long <- all_di  %>%
  filter(nparts > 40, dat %in% c("mcdb", "misc_abund", "fia")) %>%
  #mutate(dat = ifelse(nparts < 1000, paste0(dat, "_small"), dat)) %>%
  select(dat, very_small, skew_percentile, skew_percentile_excl, simpson_percentile, simpson_percentile_excl, shannon_percentile, shannon_percentile_excl, nsingletons_percentile, nsingletons_percentile_excl) %>%
  rename(skew = skew_percentile,
         skewX = skew_percentile_excl,
         simp = simpson_percentile,
         simpX = simpson_percentile_excl,
         shan = shannon_percentile,
         shanX = shannon_percentile_excl,
         nsng = nsingletons_percentile,
         nsngX = nsingletons_percentile_excl) %>%
  mutate(skewM = (skew + skewX) / 2,
         simpM = (simp+ simpX)/2,
         shanM = (shan+ shanX)/2,
         nsngM = (nsng+ nsngX)/2) %>%
  tidyr::pivot_longer(c(-dat, -very_small), names_to = "metric", values_to = "value") %>%
  mutate(metric_name = substr(metric, 0, 4),
         metric_mod = ifelse(substr(metric, 5, 5) == "X", "excl", ifelse(substr(metric, 5,5) == "M", "mean", "incl")))


ggplot(filter(all_di_shapes_long, metric_mod == "mean"), aes(value)) +
  geom_histogram(bins = 40) +
  #facet_grid(rows = vars(dat), cols = vars(metric_name), scales = "free", switch = "y") +
  facet_wrap(vars(metric_name, dat, very_small), scales = "free", ncol = 5) +
  geom_vline(xintercept = c(2.5, 97.5))


all_di_shapes_high <- all_di_shapes_long %>%
  filter(metric_mod == "excl") %>%
  group_by(dat, metric_name, very_small) %>%
  summarize(proportion_high = mean(value > 97.5),
            n = dplyr::n())

all_di_shapes_high %>%
  tidyr::pivot_wider(id_cols = c(dat, n, very_small), names_from = metric_name, values_from = proportion_high) %>% mutate(dir = "HIGH")


all_di_shapes_low <- all_di_shapes_long %>%
  filter(metric_mod == "incl") %>%
  group_by(dat, metric_name, very_small) %>%
  summarize(proportion_low = mean(value <2.5),
            n = dplyr::n())


all_di_shapes_low %>%
  tidyr::pivot_wider(id_cols = c(dat, n, very_small), names_from = metric_name, values_from = proportion_low) %>%
  mutate(dir = "LOW")


```


## Narrowness of the expectation

### Central tendency

```{r}

ggplot(filter(all_di, nparts > 20), aes(nparts, sim_pos_from_best, color = log(n0/s0))) +
  geom_point() +
  scale_x_log10()
# 
# ggplot(filter(all_di, nparts > 20, nparts < 1000), aes(nparts, sim_pos_from_best, color = log(n0/s0))) +
#   geom_point() +
#   scale_x_log10() +
#   theme(legend.position = "top")
# 
# ggplot(filter(all_di, nparts > 10, nparts < 100000), aes(nparts, sim_pos_from_best, color = log(n0/s0))) +
#   geom_point() +
#   scale_x_log10() +
#   theme(legend.position = "top")
# 
# 
# ggplot(filter(all_di, nparts > 10, nparts > 100000), aes(nparts, sim_pos_from_best, color = log(n0/s0))) +
#   geom_point() +
#   scale_x_log10() +
#   theme(legend.position = "top")
```


### Shape metrics

```{r}

ggplot(filter(all_di, nparts > 40, s0 > 2), aes(nparts, skew_95_ratio_2t, color = log(n0/s0))) +
  geom_point() +
  scale_x_log10()

ggplot(filter(all_di, nparts > 40), aes(nparts, simpson_95_ratio_2t, color = log(n0/s0))) +
  geom_point() +
  scale_x_log10()

ggplot(filter(all_di, nparts > 40), aes(nparts, shannon_95_ratio_2t, color = log(n0/s0))) +
  geom_point() +
  scale_x_log10()

ggplot(filter(all_di, nparts > 40), aes(nparts, nsingletons_95_ratio_2t, color = log(n0/s0))) +
  geom_point() +
  scale_x_log10()


```

## Resampling

### Undersampling of rare species

#### Central tendency

```{r}

all_di_singletons <- read.csv(here::here("analysis", "rev_prototyping", "all_di.csv"), stringsAsFactors = F) %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 != s0,
         s0 != 1,
         singletons,
         n0 != (s0 + 1)) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) %>%
  left_join(all_ct) %>%
  mutate(in_fia = ifelse(Dataset == "FIA", "FIA", "Other datasets")) %>%
  right_join(select(all_di, dat, site))



all_di_singletons %>%
  group_by(dat) %>%
  summarize(prop_high_po = mean(real_po_percentile_excl > 95, na.rm = T),
            nsites = dplyr::n()) %>%
  left_join(
    all_di %>%
       group_by(dat) %>%
  summarize(prop_high_po_real = mean(real_po_percentile_excl > 95, na.rm = T),
            nsites_real = dplyr::n())
  )

```

#### Shape metrics

```{r}


all_di_shapes_long <- all_di  %>%
  filter(nparts > 40) %>%
  #mutate(dat = ifelse(nparts < 1000, paste0(dat, "_small"), dat)) %>%
  select(dat, skew_percentile, skew_percentile_excl, simpson_percentile, simpson_percentile_excl, shannon_percentile, shannon_percentile_excl, nsingletons_percentile, nsingletons_percentile_excl) %>%
  rename(skew = skew_percentile,
         skewX = skew_percentile_excl,
         simp = simpson_percentile,
         simpX = simpson_percentile_excl,
         shan = shannon_percentile,
         shanX = shannon_percentile_excl,
         nsng = nsingletons_percentile,
         nsngX = nsingletons_percentile_excl) %>%
  mutate(skewM = (skew + skewX) / 2,
         simpM = (simp+ simpX)/2,
         shanM = (shan+ shanX)/2,
         nsngM = (nsng+ nsngX)/2) %>%
  tidyr::pivot_longer(-dat, names_to = "metric", values_to = "value") %>%
  mutate(metric_name = substr(metric, 0, 4),
         metric_mod = ifelse(substr(metric, 5, 5) == "X", "excl", ifelse(substr(metric, 5,5) == "M", "mean", "incl")))

all_di_shapes_high <- all_di_shapes_long %>%
  filter(metric_mod == "excl") %>%
  group_by(dat, metric_name) %>%
  summarize(proportion_high = mean(value > 97.5),
            n = dplyr::n())
all_di_shapes_low <- all_di_shapes_long %>%
  filter(metric_mod == "incl") %>%
  group_by(dat, metric_name) %>%
  summarize(proportion_low = mean(value <2.5),
            n = dplyr::n())


all_di_shapes_long_s <- all_di_singletons  %>%
  right_join(select(filter(all_di, nparts > 40), dat, site)) %>%
  #mutate(dat = ifelse(nparts < 1000, paste0(dat, "_small"), dat)) %>%
  select(dat, skew_percentile, skew_percentile_excl, simpson_percentile, simpson_percentile_excl, shannon_percentile, shannon_percentile_excl, nsingletons_percentile, nsingletons_percentile_excl) %>%
  rename(skew = skew_percentile,
         skewX = skew_percentile_excl,
         simp = simpson_percentile,
         simpX = simpson_percentile_excl,
         shan = shannon_percentile,
         shanX = shannon_percentile_excl,
         nsng = nsingletons_percentile,
         nsngX = nsingletons_percentile_excl) %>%
  mutate(skewM = (skew + skewX) / 2,
         simpM = (simp+ simpX)/2,
         shanM = (shan+ shanX)/2,
         nsngM = (nsng+ nsngX)/2) %>%
  tidyr::pivot_longer(-dat, names_to = "metric", values_to = "value") %>%
  mutate(metric_name = substr(metric, 0, 4),
         metric_mod = ifelse(substr(metric, 5, 5) == "X", "excl", ifelse(substr(metric, 5,5) == "M", "mean", "incl")))

all_di_shapes_high_s <- all_di_shapes_long_s %>%
  filter(metric_mod == "excl") %>%
  group_by(dat, metric_name) %>%
  summarize(proportion_high = mean(value > 97.5),
            n = dplyr::n())
all_di_shapes_low_s <- all_di_shapes_long_s %>%
  filter(metric_mod == "incl") %>%
  group_by(dat, metric_name) %>%
  summarize(proportion_low = mean(value <2.5),
            n = dplyr::n())





all_di_shapes_high %>%
  tidyr::pivot_wider(id_cols = c(dat, n), names_from = metric_name, values_from = proportion_high) %>% mutate(dir = "HIGH", adj = F) %>%
  bind_rows(all_di_shapes_high_s %>%
  tidyr::pivot_wider(id_cols = c(dat, n), names_from = metric_name, values_from = proportion_high) %>% mutate(dir = "HIGH", adj = T)) %>%
  arrange(dat, adj)


all_di_shapes_low %>%
  tidyr::pivot_wider(id_cols = c(dat, n), names_from = metric_name, values_from = proportion_low) %>%
  mutate(dir = "LOW", adj = F) %>%
  bind_rows(all_di_shapes_low_s %>%
       tidyr::pivot_wider(id_cols = c(dat, n), names_from = metric_name, values_from = proportion_low) %>% mutate(dir = "LOW", adj = T)) %>%
  arrange(dat, adj)




```

### Jackknife resampling

```{r}

jk_di_full <- read.csv(here::here("analysis", "rev_prototyping", "all_di_jk.csv")) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) 

jk_cts <- read.csv(here::here("analysis", "rev_prototyping", "all_ct_jk.csv")) %>%
  
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) 

jk_di <- jk_di_full %>%
  left_join(jk_cts) %>%
  group_by_all() %>%
  mutate(site_source = unlist(strsplit(site, "_")[[1]][[1]])) %>%
  ungroup() %>%
  select(dat, site, site_source, s0, n0, skew_percentile_excl,skew_percentile, simpson_percentile, simpson_percentile_excl, shannon_percentile,shannon_percentile_excl,  nsingletons_percentile, nsingletons_percentile_excl, nsingletons, nsingletons_95_ratio_2t, skew_95_ratio_2t, simpson_95_ratio_2t, shannon_95_ratio_2t, sim_pos_from_best, real_po_percentile, real_po_percentile_excl, nparts)

jk_di_means <- jk_di %>%
  group_by(dat, site_source) %>%
  summarise_at(vars(-group_cols(), -site), mean)

all_di_actual <- all_di %>%
  filter(!singletons) %>%
  mutate(site_source = as.character(site)) %>%
  select(dat, site_source,  s0, n0, skew_percentile_excl,skew_percentile, simpson_percentile, simpson_percentile_excl, shannon_percentile,shannon_percentile_excl,  nsingletons_percentile, nsingletons_percentile_excl, nsingletons, nsingletons_95_ratio_2t, skew_95_ratio_2t, simpson_95_ratio_2t, shannon_95_ratio_2t, sim_pos_from_best, real_po_percentile, real_po_percentile_excl, nparts) 

colnames(all_di_actual)[ 3:ncol(all_di_actual)] <- paste0(colnames(all_di_actual)[3:ncol(all_di_actual)], "_actual")

jk_di_results <- left_join(jk_di, all_di_actual)
jk_di_mean_results <- left_join(jk_di_means, all_di_actual)

```

#### Central tendency


```{r}
jk_di_mean_results %>%
  filter(nparts > 20) %>%
  select(dat, real_po_percentile_excl, real_po_percentile_excl_actual) %>%
  group_by(dat) %>%
  summarize(high_dissimilarity_actual = mean(real_po_percentile_excl_actual > 95, na.rm = T),
            high_dissimilarity_jk = mean(real_po_percentile_excl > 95, na.rm= T),
            n = dplyr::n())

```

#### Shape metrics


```{r}

shapecols <- c(colnames(jk_di_mean_results)[ grepl("skew", colnames(jk_di_mean_results))],
               colnames(jk_di_mean_results)[ grepl("simpson", colnames(jk_di_mean_results))],
               colnames(jk_di_mean_results)[ grepl("shannon", colnames(jk_di_mean_results))],
               colnames(jk_di_mean_results)[ grepl("nsingletons", colnames(jk_di_mean_results))])

shapecols <- shapecols[ grepl("percentile", shapecols)]

shapecols_high <- shapecols[ grepl("excl", shapecols)]

is.high <- function(x) {
  return(x > 97.5)
}

jk_shapes_high <- jk_di_mean_results %>%
  filter(nparts > 40, nparts_actual > 40) %>%
  select(dat, (shapecols_high)) %>%
  mutate_at(vars(shapecols_high), .funs = is.high) %>%
  group_by(dat) %>%
  summarize_at(vars(shapecols_high), .funs = mean) %>%
  mutate(dir = "HIGH")

shapecols_low <- shapecols[ !grepl("excl", shapecols)]
jk_shapes_high
is.low <- function(x) {
  return(x < 2.5)
}

jk_shapes_low <- jk_di_mean_results %>%
    filter(nparts > 40, nparts_actual > 40) %>%

  select(dat, (shapecols_low)) %>%
  mutate_at(vars(shapecols_low), .funs = is.low) %>%
  group_by(dat) %>%
  summarize_at(vars(shapecols_low), .funs = mean) %>%
  mutate(dir = "LOW")
jk_shapes_low
```

### Narrowness

```{r}

ggplot(jk_di_mean_results, aes(sim_pos_from_best_actual)) +
  geom_histogram(alpha = .5) +
  geom_histogram(aes(sim_pos_from_best), fill="blue", alpha = .5) +
  facet_wrap(vars(dat), scales = "free_y")

ggplot(filter(jk_di_mean_results, s0 > 2, nparts > 40, nparts_actual > 40), aes(skew_95_ratio_2t_actual)) +
  geom_histogram(alpha = .5) +
  geom_histogram(aes(skew_95_ratio_2t), fill="blue", alpha = .5) +
  facet_wrap(vars(dat), scales = "free_y")


ggplot(filter(jk_di_mean_results, nparts > 40, nparts_actual > 40), aes(simpson_95_ratio_2t_actual)) +
  geom_histogram(alpha = .5) +
  geom_histogram(aes(simpson_95_ratio_2t), fill="blue", alpha = .5) +
  facet_wrap(vars(dat), scales = "free_y")

ggplot(filter(jk_di_mean_results, nparts > 40, nparts_actual > 40), aes(shannon_95_ratio_2t_actual)) +
  geom_histogram(alpha = .5) +
  geom_histogram(aes(shannon_95_ratio_2t), fill="blue", alpha = .5) +
  facet_wrap(vars(dat), scales = "free_y")

ggplot(filter(jk_di_mean_results, nparts > 40, nparts_actual > 40), aes(nsingletons_95_ratio_2t_actual)) +
  geom_histogram(alpha = .5) +
  geom_histogram(aes(nsingletons_95_ratio_2t), fill="blue", alpha = .5) +
  facet_wrap(vars(dat), scales = "free_y")


```
