---
title: "Central tendency"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

knitr::opts_chunk$set(fig.width=6, fig.height=6, warning = FALSE, message = FALSE) 

theme_set(theme_bw())


all_di <- read.csv(here::here("analysis", "rev_prototyping", "all_di.csv"), stringsAsFactors = F)

all_ct <-  read.csv(here::here("analysis", "rev_prototyping", "all_ct.csv"), stringsAsFactors = F)

fia_ct <- read.csv(here::here("fia_cts.csv"))

all_ct <- rbind(all_ct, fia_ct)

all_ct <- all_ct %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat))

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 != s0,
         s0 != 1,
         !singletons,
         n0 != (s0 + 1)) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) %>%
  left_join(all_ct)
```


```{r}

ggplot(all_di, aes(sim_pos_from_best)) +
  geom_histogram() +
  facet_wrap(vars(dat), scales = "free_y") 

ggplot(all_di, aes(real_po_percentile_excl)) + geom_histogram() +
  facet_wrap(vars(dat), scales = "free_y") + geom_vline(xintercept = 95)

all_di %>%
  group_by(dat) %>%
  summarize(prop_high_po = mean(real_po_percentile_excl > 95, na.rm = T),
            nsites = dplyr::n())

ggplot(all_di, aes(sim_pos_from_best, real_po, color = real_po_percentile_excl > 95)) +
  geom_point(alpha = .3) +
  geom_abline(slope = 1, intercept = 0) +
  theme(legend.position = "top") +
  scale_color_viridis_d(end = .8) +
  facet_wrap(vars(dat), scales = "fixed")


ggplot(all_di, aes((real_po / sim_pos_from_best), real_po_percentile_excl, color =  real_po_percentile_excl > 95)) +
  geom_point(alpha = .3) 


all_di %>%
  mutate(rat = real_po / sim_pos_from_best,
         dev = real_po_percentile_excl > 95) %>%
  group_by(dev) %>%
  summarize(minrat = min(rat),
            maxrat = max(rat),
            meanrat = mean(rat),
            mindis = min(real_po - sim_pos_from_best),
            maxdis = max(real_po - sim_pos_from_best))

ggplot(all_di, aes(nparts, sim_pos_from_best)) +
  geom_point() +
  scale_x_log10()


ggplot(all_di, aes(nparts, sim_pos_from_best, color = dat)) +
  geom_point() +
  scale_x_log10()  +
  scale_color_viridis_d() +
  theme(legend.position = "top")


ggplot(all_di, aes(s0, n0, color =  sim_pos_from_best)) +
  geom_point() +
  scale_x_log10()  +
  scale_y_log10() +
  scale_color_viridis_c() +
  theme(legend.position = "top")
```


<!-- ```{r} -->

<!-- ggplot(all_di, aes(sim_r2_from_best_median)) + -->
<!--   geom_histogram() -->


<!-- ggplot(all_di, aes(sim_r2_from_best_median, real_r2)) + -->
<!--   geom_point() + -->
<!--   geom_line(aes(sim_r2_from_best_median, sim_r2_from_best_median)) + -->
<!--   ylim(0,1) -->


<!-- ggplot(all_di, aes(real_po_percentile_excl)) + geom_histogram() -->

<!-- ggplot(all_di, aes(nparts, sim_r2_from_best_median)) + -->
<!--   geom_point() + -->
<!--   scale_x_log10() -->

<!-- ``` -->
