---
title: "Comparing to lognormal, Poisson, exponential"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(scadsanalysis)

knitr::opts_chunk$set(fig.width=4, fig.height=3, warning = FALSE, message = FALSE) 

theme_set(theme_bw())

```
FIA 16059000010 - 7, 50. Small

BBS 4229 - 50, 709. High n

Gentry 82 - 214, 333. High n but low N/S

```{r}

fia_small <- load_dataset("fia_small")

small <- fia_small %>%
  filter(!singletons, site == "16059000010")

bbs <- load_dataset("bbs")

big <- bbs %>%
  filter(site == "4229")

gentry <- load_dataset("gentry")

wide <- gentry %>% filter(site == "82")


small_fs <- read.csv(here::here("analysis", "rev_prototyping", "fia_16059000010_fs.csv"))
big_fs <- read.csv(here::here("analysis", "rev_prototyping", "bbs_4229_fs.csv"))
wide_fs <- read.csv(here::here("analysis", "rev_prototyping", "gentry_82_fs.csv"))


ggplot(small, aes(rank, abund)) + 
  geom_line(data = small_fs, aes(rank, abund, group = sim), alpha = .01) +   geom_point(color = "red") 



ggplot(big, aes(rank, abund)) + 
  geom_point()


ggplot(big, aes(rank, abund)) + 
  geom_line(data = big_fs, aes(rank, abund, group = sim), alpha = .01) +  geom_point(color = "red") 

ggplot(wide, aes(rank, abund)) + 
  geom_point()


ggplot(wide, aes(rank, abund)) + 
  geom_line(data = wide_fs, aes(rank, abund, group = sim), alpha = .01) +  geom_point(color = "red") + ylim(0, 40)

```


```{r}
library(MASS)

small_exp <- fitdistr(small$abund, "exponential")

small_exp_preds <- replicate(n = 4000, expr = sort(round(rexp(nrow(small), rate = small_exp$estimate))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund") %>%
  group_by(sim) %>%
  mutate(skewness = e1071::skewness(abund),
         evenness = vegan::diversity(abund, index = "shannon")) %>%
  ungroup()

ggplot(small, aes(rank, abund))+   geom_line(data = small_exp_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 

small_fs <- small_fs %>% 
  group_by(sim) %>%
  mutate(skewness = e1071::skewness(abund),
         evenness = vegan::diversity(abund, index = "shannon")) %>%
  ungroup()

ggplot(small_exp_preds, aes(skewness)) +
  geom_histogram() + 
  geom_vline(xintercept = e1071::skewness(small$abund))

ggplot(filter(small_fs, sim > 0), aes(skewness)) +
  geom_histogram() + 
  geom_vline(xintercept = e1071::skewness(small$abund))


big_exp <- fitdistr(big$abund, "exponential")

big_exp_preds <- replicate(n = 4000, expr = sort(round(rexp(nrow(big), rate = big_exp$estimate))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(big, aes(rank, abund))+   geom_line(data = big_exp_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 


wide_exp <- fitdistr(wide$abund, "exponential")

wide_exp_preds <- replicate(n = 4000, expr = sort(round(rexp(nrow(wide), rate = wide_exp$estimate))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(wide, aes(rank, abund))+   geom_line(data = wide_exp_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 
```


```{r}


small_pois <- fitdistr(small$abund, "poisson")

small_pois_preds <- replicate(n = 4000, expr = sort(round(rpois(nrow(small), lambda = small_pois$estimate))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(small, aes(rank, abund))+   geom_line(data = small_pois_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 


big_pois <- fitdistr(big$abund, "poisson")

big_pois_preds <- replicate(n = 4000, expr = sort(round(rpois(nrow(big), lambda = big_pois$estimate))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(big, aes(rank, abund))+   geom_line(data = big_pois_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 


wide_pois <- fitdistr(wide$abund, "poisson")

wide_pois_preds <- replicate(n = 4000, expr = sort(round(rpois(nrow(wide), lambda = wide_pois$estimate))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(wide, aes(rank, abund))+   geom_line(data = wide_pois_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 
```

```{r}


small_lnorm <- fitdistr(small$abund, "lognormal")

small_lnorm_preds <- replicate(n = 4000, expr = sort(round(rlnorm(nrow(small), meanlog = small_lnorm$estimate["meanlog"], sdlog = small_lnorm$estimate["sdlog"]))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(small, aes(rank, abund))+   geom_line(data = small_lnorm_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") + ylim(0, 50)


big_lnorm <- fitdistr(big$abund, "lognormal")

big_lnorm_preds <- replicate(n = 4000, expr = sort(round(rlnorm(nrow(big), meanlog = big_lnorm$estimate["meanlog"], sdlog = big_lnorm$estimate["sdlog"]))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")
ggplot(big, aes(rank, abund))+   geom_line(data = big_lnorm_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") + ylim(0, 250)


wide_lnorm <- fitdistr(wide$abund, "lognormal")

wide_lnorm_preds <- replicate(n = 4000, expr = sort(round(rlnorm(nrow(wide), meanlog = wide_lnorm$estimate["meanlog"], sdlog = wide_lnorm$estimate["sdlog"]))), simplify = T) %>%
  as.data.frame() %>%
  mutate(rank = dplyr::row_number()) %>%
  tidyr::pivot_longer(-rank, names_to = "sim", values_to = "abund")

ggplot(wide, aes(rank, abund))+   geom_line(data = wide_lnorm_preds, aes(rank, abund, group = sim), alpha = .01)  + geom_point(color = "red") 
```

