---
title: "Prop off"
author: Renata Diaz
date: "`r Sys.Date()`"
output: 
    github_document:
       df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)
library(grid)
theme_set(theme_bw())

all_di <- read.csv(here::here("analysis", "rev_prototyping", "mcdb_di.csv")) 

all_di <- all_di %>%
  filter(s0 > 1,
         s0 != n0,
         n0 != s0 + 1,
         !singletons) 

sum(all_di$nsingeltons_median == all_di$nsingletons_95)

ggplot(filter(all_di, nsingletons_95 > nsingeltons_median), aes(nsingletons_percentile)) +
  geom_histogram()

ggplot(filter(all_di, nsingletons_95 > nsingeltons_median), aes(nsingletons_percentile_excl)) +
  geom_histogram()

```


```{r}
di_10 <- read.csv(here::here("misc_10_di.csv"))

ggplot(filter(di_10, source == "sampled"), aes(nsingletons)) +
  geom_histogram() +
  geom_vline(xintercept = filter(di_10, source == "observed")$nsingletons)

di_11 <- read.csv(here::here("misc_11_di.csv"))

ggplot(filter(di_11, source == "sampled"), aes(nsingletons)) +
  geom_histogram() +
  geom_vline(xintercept = filter(di_11, source == "observed")$nsingletons)

di_22 <- read.csv(here::here("misc_22_di.csv"))

ggplot(filter(di_22, source == "sampled"), aes(nsingletons)) +
  geom_histogram() +
  geom_vline(xintercept = filter(di_22, source == "observed")$nsingletons)

filter(all_di, site %in% c(10, 11, 22), !singletons)  %>%
  select(site, nsingletons_percentile, nsingletons_percentile_excl)

```
