---
title: "Synthesis report"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(drake)
library(dplyr)
library(ggplot2)

all_di <- read.csv(here::here("analysis", "reports", "all_di.csv"), stringsAsFactors = F)

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log150_nparts = log(gmp:::as.double.bigz(nparts), base = 150)) %>%
  filter(s0 >= 2,
         n0 > s0)
```

# Datasets in S and N space

Here is where our communities fall in S and N space:

```{r datasets in s and n space}
ggplot(filter(all_di, singletons == F), aes(x = log(s0), y = log(n0), color = dat)) +
  geom_point(alpha = .8) +
  theme_bw() +
  theme(legend.position = "top") + scale_color_viridis_d()

```

```{r skew intervals by dataset}

ggplot(filter(all_di, !singletons), aes(x = skew_95_ratio_2t)) +
  geom_histogram() +
  facet_wrap(vars(dat), scales = "free_y")

ggplot(filter(all_di, !singletons), aes(x = skew_95_ratio_1t)) +
  geom_histogram() +
  facet_wrap(vars(dat), scales = "free_y")
```
